web:
  restart: always
  container_name: gitmonitor-web
  environment:
    ENV: production
  build: docker/app
  volumes:
    - "/Users/manuel/Dropbox/Synced/PHP/gitmonitor-server/app:/src/app"
  expose:
    - "3000"
  ports:
    - "3000:3000"
  command: forever /src/app/server/server.js
  links:
    - mongo:mongo

mongo:
  restart: always
  container_name: gitmonitor-mongo
  environment:
    ENV: production
  build: docker/mongo
  volumes:
    - "/mongo-dev:/data/db"
  expose:
    - "27017"
  ports:
    - "127.0.0.1:27017:27017"
  command: mongod --noprealloc --smallfiles
