web:
  restart: always
  environment:
    ENV: dev
  build: docker/app
  volumes:
    - "./app:/src/app"
  expose:
    - "3000"
  ports:
    - "3000:3000"
  links:
    - mongo:mongo
  command: forever /src/app/server/server.js

mongo:
  restart: always
  environment:
    ENV: dev
  image: mongo:3.0
  volumes:
    - "/mongo-dev:/data/db"
  expose:
    - "27017"
  ports:
    - "127.0.0.1:27017:27017"
  command: mongod --noprealloc --smallfiles
