web:
  restart: always
  environment:
    NODE_ENV: development
  build: docker/app
  volumes:
    - "./app:/src/app"
  expose:
    - "3000"
  ports:
    - "3000:3000"
  links:
    - mongo:mongo
  command: tail -f /dev/null

mongo:
  restart: always
  build: docker/mongo
  volumes:
    - "/mongo-dev:/data/db"
  expose:
    - "27017"
  command: mongod --noprealloc --smallfiles
