version: "2"
services:
  web:
    restart: always
    environment:
      NODE_ENV: production
    build:
      context: .
      dockerfile: ./Dockerfile-web
    expose:
      - "3000"
    ports:
      - "3000:3000"
    links:
      - mongo:mongo

  mongo:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile-mongo
    volumes:
      - "/mongo-dev:/data/db"
    expose:
      - "27017"
    command: mongod --noprealloc --smallfiles
