web:
  restart: always
  container_name: gitmonitor-web
  environment:
    NODE_ENV: production
  build: docker/app
  volumes:
    - "./app:/src/app"
  expose:
    - "3000"
  ports:
    - "3000:3000"
  command: forever /src/app/server/server.js
  links:
    - mongo:mongo

mongo:
  restart: always
  container_name: gitmonitor-mongo
  build: docker/mongo
  volumes:
    - "/mongo-dev:/data/db"
  expose:
    - "27017"
  command: mongod --noprealloc --smallfiles
